name: CrazyAuctionsPlus
authors:
- BadBones69
- TRCStudioDean
main: studio.trc.bukkit.crazyauctionsplus.Main
version: 1.3.0.0
api-version: 1.13
description: Plus version of CrazyAuctions plugin, by TRCStudioDean (TRC Studio & PA Project), The original author was BadBones69.
commands:
    ca:
        description: Crazy Auctions Plus Main command.
        aliases: [cap, crazyauction, crazyauctions, crazyauctionsplus]